# Generated by Django 3.2 on 2021-04-13 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_article_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='post_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
