# Generated by Django 3.2 on 2021-04-13 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_article_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='post_image',
        ),
    ]
