# Generated by Django 3.2 on 2021-04-13 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_remove_article_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
