# Generated by Django 3.2 on 2021-04-15 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_remove_contact_l_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='l_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
