# Generated by Django 3.2 on 2021-04-16 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='categories',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.categories'),
        ),
    ]
